// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AllTablesWithRelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllTablesWithRelations));
        
        string IMigrationMetadata.Id
        {
            get { return "202212091447491_AllTablesWithRelations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
